name: CI/CD Pipeline

on:
  push:
    branches:
      - main
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Maven
        uses: actions/setup-Maven@v2
        with:
           Maven-version: '3_2_5'


      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

     # 

     # - name: Install dependencies
    #    run: npm install
 
  #    - name: Build Application
#        run: |
 #         # Add commands to build your application
   #       ./gradlew build  # or npm install, mvn package, etc

   #   - name: Checkmarx AST CLI Action
   #     uses: checkmarx/ast-github-action@main #Github Action version
    #    with:
    #      base_uri: https://ast.checkmarx.net/
      #    cx_tenant: your_tenant
      #    cx_client_id: ${{ secrets.CX_CLIENT_ID }}
        #  cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}

      

      
